version: '3'

services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=devops
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_ROOT_HOST='%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6666:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=12345 --execute \"SHOW DATABASES\""
      interval: 4s
      timeout: 20s
      retries: 5
      start_period: 10s