apiVersion: v1
kind: Service
metadata:
  name: coupon-app
  labels:
    app: coupon-app
spec:
  type: NodePort
  selector:
    app: coupon-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30288