apiVersion: v1
kind: Service
metadata:
  name: flight-app
  labels:
    app: flight-app
spec:
  type: NodePort
  selector:
    app: flight-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30290