apiVersion: v1
kind: Service
metadata:
  name: product-app
  labels:
    app: product-app
spec:
  type: NodePort
  selector:
    app: product-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30289